version: "3.8"
networks:
  dev:

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
      - frontend
    networks:
      - dev

  app:
    build:
      context: ./jarvis-hikVision-integration
    container_name: jarvis-hikVision-api
    ports:
      - "3000:3000"
    volumes:
      - ./jarvis-hikVision-integration:/home/node/app:cached
      - ./jarvis-hikVision-integration/data:/home/node/app/data
      - /home/node/app/node_modules
    restart: always
    environment:
      - PORT=3000
      - TZ=Asia/Almaty
    networks:
      - dev

  frontend:
    build:
      context: ./jarvis-skud
    container_name: jarvis-hikVision-frontend
    ports:
      - "8080:80"
    restart: always
    environment:
      - TZ=Asia/Almaty
    networks:
      - dev

  ngrok:
    image: ngrok/ngrok
    container_name: ngrok
    environment:
      - NGROK_AUTHTOKEN=2mkQmHizEd1ygXxSsZVZIdSoCre_5LJYLXJM5nfTmHPLzY5Pd
    command: http app:3000 --url=jarvis.ngrok.pro
    depends_on:
      - app
    networks:
      - dev

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: jarvis_survmenu_admin
      POSTGRES_PASSWORD: 8mba1JYebC
      POSTGRES_DB: survdatabase
      TZ: Asia/Almaty
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - dev

volumes:
  pgdata:
